[package]
name = "koterahq/gcs"
author = ["akowa-ss"]
license = "MIT"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.2.0"
Red = "uncontained0/red@1.2.2"